AWSTemplateFormatVersion: '2010-09-09'
Description: Certificate for CloudFront using DNS validation

Resources:
  ReubenCertV2:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: reubenmulholland.com
      SubjectAlternativeNames:
        - www.reubenmulholland.com
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Value: !Ref ReubenCertV2
