version = 0.1
[cert.deploy.parameters]
stack_name = "cloud-resume-cert"
resolve_s3 = true
s3_prefix = "cloud-resume-cert"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
