AWSTemplateFormatVersion: '2010-09-09'
Description: DNS records for reubenmulholland.com pointing to prod CloudFront

Parameters:
  HostedZoneId:
    Type: String
    Description: Route53 hosted zone ID for reubenmulholland.com (the zone in ROOT)
  ApexTargetDomainName:
    Type: String
    Description: Domain name of prod CloudFront distribution (e.g., d123abc.cloudfront.net)
  WwwTargetDomainName:
    Type: String
    Default: ""
    Description: Domain name of WWW redirect CloudFront distribution (optional)

Conditions:
  HasWww: !Not [ !Equals [ !Ref WwwTargetDomainName, "" ] ]

Resources:
  ApexARecord:
    Type: AWS::Route53::RecordSet
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: reubenmulholland.com
      Type: A
      AliasTarget:
        # CloudFront hosted zone ID (global, static)
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !Ref ApexTargetDomainName

  WwwARecord:
    Type: AWS::Route53::RecordSet
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Condition: HasWww
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: www.reubenmulholland.com
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !Ref WwwTargetDomainName

