AWSTemplateFormatVersion: '2010-09-09'
Description: DNS records for reubenmulholland.com pointing to prod CloudFront

Parameters:
  HostedZoneIdSsmPath:
    Type: String
    Default: /cloud-resume/root/hosted_zone_id
    Description: SSM path in ROOT that stores the Hosted Zone ID

  ApexTargetDomainName:
    Type: String
    Description: dxxxx.cloudfront.net from PROD outputs

  WwwTargetDomainName:
    Type: String
    Default: ""
    Description: dxxxx.cloudfront.net (optional, for www)

Conditions:
  HasWww: !Not [ !Equals [ !Ref WwwTargetDomainName, "" ] ]

Resources:
  ApexARecord:
    Type: AWS::Route53::RecordSet
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      HostedZoneId: !Sub "{{resolve:ssm:${HostedZoneIdSsmPath}}}"
      Name: reubenmulholland.com
      Type: A
      AliasTarget:
        # CloudFront hosted zone ID (global, static)
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !Ref ApexTargetDomainName

  WwwARecord:
    Type: AWS::Route53::RecordSet
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Condition: HasWww
    Properties:
      HostedZoneId: !Sub "{{resolve:ssm:${HostedZoneIdSsmPath}}}"
      Name: www.reubenmulholland.com
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !Ref WwwTargetDomainName

