name: pr
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Set up venv & deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r resume-infra/tests/requirements.txt
      - name: Run unit tests (integration auto-skips w/o creds)
        run: |
          source .venv/bin/activate
          pytest -q
