name: rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Where to redeploy"
        required: true
        type: choice
        options: [eng, test, prod]
      sha:
        description: "Commit SHA (full or short)"
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  STACK_NAME: cloud-resume-infra
  PROMO_BUCKET: cloud-resume-promo-central-515275665162
  APP_PREFIX: cloud-resume-infra

jobs:
  redeploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}   # keeps approvals
    permissions: { id-token: write, contents: read }

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets[format('AWS_ROLE_{0}', github.event.inputs.environment)] }}

      # 1) Resolve artifact and expose the matched SHA as a step output
      - name: Resolve & download packaged.yaml (allow short SHA)
        id: resolve
        run: |
          set -euo pipefail
          BASE="s3://${PROMO_BUCKET}/${APP_PREFIX}/"
          INPUT="${{ github.event.inputs.sha }}"
          MATCH=$(aws s3 ls "$BASE" | awk '{print $2}' | sed 's/\/$//' | grep -E "^${INPUT}" | head -n1 || true)
          if [ -z "$MATCH" ]; then
            echo "No artifacts under ${BASE}${INPUT}*/"
            echo "Available prefixes:" && aws s3 ls "$BASE" || true
            exit 1
          fi
          echo "Using SHA: $MATCH"
          echo "match=$MATCH" >> "$GITHUB_OUTPUT"
          aws s3 cp "s3://${PROMO_BUCKET}/${APP_PREFIX}/${MATCH}/packaged.yaml" packaged.yaml

      # 2) Infra rollback (deploy the selected packaged.yaml)
      - name: Deploy selected infra artifact (CloudFormation)
        run: |
          aws cloudformation deploy \
            --template-file packaged.yaml \
            --stack-name "${STACK_NAME}" \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --parameter-overrides EnvironmentName=${{ github.event.inputs.environment }} \
            --no-fail-on-empty-changeset

      # 3) Discover hosting bucket and CloudFront distribution; expose as outputs
      - name: Locate hosting bucket & distribution (current env)
        id: discover
        run: |
          set -euo pipefail
          BUCKET=$(aws cloudformation describe-stacks \
            --stack-name "${STACK_NAME}" \
            --query "Stacks[0].Outputs[?OutputKey=='LandingPage'].OutputValue" \
            --output text)
          DIST=$(aws cloudformation describe-stacks \
            --stack-name "${STACK_NAME}" \
            --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" \
            --output text)
          echo "bucket=$BUCKET" >> "$GITHUB_OUTPUT"
          echo "dist_id=$DIST"  >> "$GITHUB_OUTPUT"

      # 4) Optional frontend rollback from the same SHA (if site snapshot exists)
      - name: Restore frontend files for selected SHA (if present)
        env:
          MATCH_SHA: ${{ steps.resolve.outputs.match }}
          DEST_BUCKET: ${{ steps.discover.outputs.bucket }}
        run: |
          set -euo pipefail
          if [ -z "${MATCH_SHA:-}" ] || [ "${MATCH_SHA}" = "None" ]; then
            echo "No resolved SHA from 'resolve' step; skipping site restore."
            exit 0
          fi
          SRC_PREFIX="s3://${PROMO_BUCKET}/${APP_PREFIX}/${MATCH_SHA}/site/"
          if aws s3 ls "$SRC_PREFIX" >/dev/null 2>&1; then
            echo "Restoring frontend from $SRC_PREFIX -> s3://${DEST_BUCKET}"
            aws s3 sync "$SRC_PREFIX" "s3://${DEST_BUCKET}" --delete
          else
            echo "No frontend snapshot found at $SRC_PREFIX; skipping site restore."
          fi

      # 5) Make the rollback visible
      - name: Invalidate CloudFront (make rollback visible)
        if: ${{ steps.discover.outputs.dist_id && steps.discover.outputs.dist_id != 'None' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ steps.discover.outputs.dist_id }}" \
            --paths "/*"
